cff_forms_templates = {
    "free": [{
            "title": "Blank form",
            "category": "Basic Operations",
            "description": "Blank form to start from scratch.",
			"thumb":"35.png",
			"id": 35
        }, {
            "title": "Simple Operations",
            "category": "Basic Operations",
            "description": "Sum of numbers fields and the sum of ticked choices in a multi-choices field.",
			"thumb": "1.png",
			"id": 1
        }, {
            "title": "Contact Form",
            "category": "Basic Operations",
            "description": "Basic contact form.",
			"thumb": "19.png",
            "id": 19
        }, {
            "title": "Checkbox and Radio Buttons with Images",
            "category": "Basic Operations",
            "description": "Use img tags in the texts of checkboxes and radio buttons.",
			"thumb":"21.png",
            "id": 21
        }, {
            "title": "DropDown fields with Images",
            "category": "Basic Operations",
            "description": "To display images in DropDown fields, you must enter img tags as their choices texts, and tick the Apply Select2 library attribute in its settings.",
			"thumb":"22.png",
            "id": 22
        }, {
            "title": "Multi-Page Form",
            "category": "Basic Operations",
            "description": "Multipage contact form. Inserts page break controls between fields belonging to different pages.",
			"thumb":"23.png",
            "id": 23
        }, {
            "title": "Dependencies",
            "category": "Basic Operations",
            "description": "Define dependencies between fields.",
			"thumb":"24.png",
            "id": 24
        }, {
            "title": "Dependencies with Operations",
            "category": "Basic Operations",
            "description": "Activating / deactivating fields with the ACTIVATEFIELD and IGNOREFIELD operations.",
			"thumb":"68.png",
            "id": 68
        }, {
            "title": "Password Strength Checker",
            "category": "Basic Operations",
            "description": "Checks password strength using a color-coded system.",
			"thumb":"70.png",
            "id": 70
        }, {
            "title": "Converting Values",
            "category": "Basic Operations",
            "description": "Convert a value from one unit of measurement to another.",
			"thumb":"25.png",
            "id": 25
        }, {
            "title": "Form With Optional Fields",
            "category": "Basic Operations",
            "description": "An order form that allows you to add new products or delete existing ones.",
			"thumb":"20.png",
            "id": 20
        }, {
            "title": "Print Form Button",
            "category": "Basic Operations",
            "description": "The print form button allows you to print only the form, excluding the rest of the page. Assigning the class name cff-no-print to the fields allows you to exclude them from the printed form.",
			"thumb":"26.png",
            "id": 26
        }, {
            "title": "Decimal Places",
            "category": "Basic Operations",
            "description": "Determine the number of decimal places in the result of the equation using the PREC operation.",
			"thumb":"27.png",
            "id": 27
        }, {
            "title": "Recording User Audio and Video",
            "category": "Basic Operations",
            "description": "Allows you to record an audio or video of the user that you can use as proof of acceptance of a contract or terms of service.",
			"thumb":"28.png",
            "id": 28
        }, {
            "title": "Land Area Calculator",
            "category": "Basic Operations",
            "description": "Calculates the maximum area of a plot based on the size of its sides. Calculates the area of a polygon of n-sides (3<=n).",
			"thumb":"30.png",
            "id": 30
        }, {
            "title": "Storage Requirements",
            "category": "Basic Operations",
            "description": "Calculates the area required for furniture storage.",
			"thumb":"45.png",
            "id": 45
        }, {
            "title": "Automobile Information",
            "category": "Basic Operations",
            "description": "Collects automobiles' makes, models, and other information. It uses datalists to facilitate data entry for users.",
			"thumb":"31.png",
            "id": 31
        }, {
            "title": "Visitor Details",
            "category": "Basic Operations",
            "description": "Identifies the IP address, region, coordinates, timezone, country, city, and other details of the form visitor.",
			"thumb":"62.png",
            "id": 62
        }, {
            "title": "Carbon Footprint Calculator",
            "category": "Lifestyle",
            "description": "Calculate your annual carbon footprint based on your lifestyle choices (Generated by Claude AI).",
			"thumb": "73.png",
			"id": 73
        }, {
            "title": "Solar Power Investment Calculator",
            "category": "Lifestyle|Financial",
            "description": "Calculate if installing solar panels for your home is feasible and how long it will take to recoup your investment (Generated by Claude AI).",
			"thumb": "74.png",
			"id": 74
        }, {
            "title": "Simple Accommodation Booking",
            "category": "Dates Operations",
            "description": "Gives a quote for a stay in a hotel based in the check-in date, check-out date and some optional services.",
			"thumb": "2.png",
			"id": 2
        }, {
            "title": "AI - Language Translator",
            "category": "AI",
            "description": "The form uses the AI for translating the texts.",
			"thumb":"69.png",
            "id": 69
        }, {
            "title": "Working Days",
            "category": "Dates Operations",
            "description": "Calculates the working days between two dates, excluding specific days of the week.",
			"thumb":"8.png",
            "id": 8
        }, {
            "title": "Dates Difference",
            "category": "Dates Operations",
            "description": "It calculates the difference between two dates using the DATEDIFF operation.",
			"thumb":"55.png",
            "id": 55
        }, {
            "title": "Increasing Dates",
            "category": "Dates Operations",
            "description": "Adds X days to a date by excluding specific days of the week.",
			"thumb":"17.png",
            "id": 17
        }, {
            "title": "Time to Retirement",
            "category": "Dates Operations",
            "description": "Calculates time to retirement based on age of bird and retirement age.",
			"thumb":"41.png",
            "id": 41
        }, {
            "title": "Pet Age",
            "category": "Dates Operations",
            "description": "Calculates pet age in human years.",
			"thumb":"52.png",
            "id": 52
        }, {
            "title": "Booking Form",
            "category": "Dates Operations",
            "description": "Booking form based on date interval, number of people, rooms, and additional services.",
			"thumb":"44.png",
            "id": 44
        }, {
            "title": "Holidays",
            "category": "Dates Operations",
            "description": "Retrieves the list of holidays for specific countries and years from Nager.Date",
			"thumb":"60.png",
            "id": 60
        }, {
            "title": "Ideal Weight Calculator",
            "category": "Health",
            "description": "Uses a simple formula but with a conditional rule (if male or female).",
			"thumb": "3.png",
            "id": 3
        }, {
            "title": "Pregnancy Calculator",
            "category": "Health",
            "description": "Calculates the conception date and due date based in the first day of last menstrual period.",
			"thumb": "4.png",
            "id": 4
        }, {
            "title": "BMI",
            "category": "Health",
            "description": "Body Mass Index is a calculation that is used to determine if a person is overweight that applies to both adult men and women.",
			"thumb":"6.png",
            "id": 6
        }, {
            "title": "Calories Calculator",
            "category": "Health",
            "description": "Calculate the number of calories a person needs to consume each day to maintain his or her weight.",
			"thumb":"7.png",
            "id": 7
        }, {
            "title": "Calories Calculator - Imperial and Metric",
            "category": "Health",
            "description": "Calculate the number of calories a person needs to consume each day for weight maintenance and the activity level alternatives.",
			"thumb":"32.png",
            "id": 32
        }, {
            "title": "Macronutrients Calculator",
            "category": "Health",
            "description": "Calculate the essential nutrients based on individual physical condition, activity, and goals.",
			"thumb":"39.png",
            "id": 39
        }, {
            "title": "Daily Hydratation Calculator",
            "category": "Health",
            "description": "Calculate the daily water intake based on gender, age, activity level, and climate.",
			"thumb":"33.png",
            "id": 33
        }, {
            "title": "Daily Hydratation Calculator",
            "category": "Health",
            "description": "Calculate the daily water intake based on weight, activity level, and climate.",
			"thumb":"38.png",
            "id": 38
        }, {
            "title": "Weight Goal",
            "category": "Health",
            "description": "Calculates the daily calories you should eat to reach a weight goal.",
			"thumb":"29.png",
            "id": 29
        }, {
            "title": "Hip-to-Waist Ratio",
            "category": "Health",
            "description": "Hip to Waist Ratio (HWR) is an essential indicator of the body’s fat distribution and overall health.",
			"thumb":"46.png",
            "id": 46
        }, {
            "title": "Percentile Deviation",
            "category": "Health",
            "description": "Calculate the percentile deviation of a baby's height based on their age in months.",
			"thumb":"54.png",
            "id": 54
        }, {
            "title": "Lease Calculator",
            "category": "Financial",
            "description": "Lease calculator based on loan amount, residual value, interest rate, and time interval.",
			"thumb":"5.png",
            "id": 5
        }, {
            "title": "Simple Interest Calculator",
            "category": "Financial",
            "description": "Calculate the earning or interest payment only from what was borrowed, the original amount invested or the face value of a bond.",
			"thumb":"10.png",
            "id": 10
        }, {
            "title": "Compound Interest Calculator (For savings and loans)",
            "category": "Financial",
            "description": "Compound Interest refers to earning or paying interest on interest.",
			"thumb":"11.png",
            "id": 11
        }, {
            "title": "SIP Investment Calculator",
            "category": "Financial",
            "description": "Calculate the invested amount, estimated return, and the total value.",
			"thumb":"34.png",
            "id": 34
        }, {
            "title": "Form 1040 U.S. Individual Income Tax Return",
            "category": "Financial",
            "description": "This form calculates federal income tax liability based on income, deductions, and credits (Generated by Claude AI).",
			"thumb":"71.png",
            "id": 71
        }, {
            "title": "Schedule C - Business Income and Expenses",
            "category": "Financial",
            "description": "Used by sole proprietors to report income and expenses from a business (Generated by Claude AI).",
			"thumb":"72.png",
            "id": 72
        }, {
            "title": "Exchange Rate Form",
            "category": "Financial",
            "description": "Uses the cffProxy operation to call an exchange rate API.",
			"thumb":"13.png",
            "id": 13
        }, {
            "title": "European VAT",
            "category": "Financial",
            "description": "Get the European countries VAT.",
			"thumb":"14.png",
            "id": 14
        }, {
            "title": "Check VAT Number",
            "category": "Financial",
            "description": "Checks the validity of a VAT number and displays additional details about the company.",
			"thumb":"61.png",
            "id": 61
        }, {
            "title": "Pay Raise Percent Calculator",
            "category": "Financial",
            "description": "Allows users to easily determine their pay raise/decrease percentage, salary differentials, and more.",
			"thumb":"42.png",
            "id": 42
        }, {
            "title": "Life Insurance Calculator",
            "category": "Financial",
            "description": "Life Insurance Calculator calculate life insurance based on age, annual income, number of dependents, and current liabilities.",
			"thumb":"43.png",
            "id": 43
        }, {
            "title": "Home Energy Savings",
            "category": "Financial",
            "description": "Calculate the potential savings from undergoing a home energy improvement.",
			"thumb":"47.png",
            "id": 47
        }, {
            "title": "Car Payment Calculator",
            "category": "Financial",
            "description": "Tool for dealerships looking to assist customers with automobile financing.",
			"thumb":"48.png",
            "id": 48
        }, {
            "title": "Retirement Age Calculator",
            "category": "Financial",
            "description": "Calculate the age when the person will meet the minimum required years of work.",
			"thumb":"49.png",
            "id": 49
        }, {
            "title": "Net Salary Calculator",
            "category": "Financial",
            "description": "Calculate the net salary based on gross salary and country.",
			"thumb":"53.png",
            "id": 53
        }, {
            "title": "Biance Wall",
            "category": "Financial|Crypto|Service",
            "description": "Real-time market data for all trading pairs on the Binance exchange.",
			"thumb":"56.png",
            "id": 56
        }, {
            "title": "CoinCap Wall",
            "category": "Financial|Crypto|Service",
            "description": "Real-time cryptocurrency prices.",
			"thumb":"57.png",
            "id": 57
        }, {
            "title": "CoinDesk Bitcoin Price",
            "category": "Financial|Crypto|Service",
            "description": "Calculate the value of your bitcoins in other currencies.",
			"thumb":"58.png",
            "id": 58
        }, {
            "title": "Cryptocurrency Market Data",
            "category": "Financial|Crypto|Service",
            "description": "Calculate cryptocurrency prices with CoinGecko. Choose your preferred currency for accurate conversions.",
			"thumb":"59.png",
            "id": 59
        }, {
            "title": "Transportation Cost",
            "category": "Transportation",
            "description": "Basic algorithm to calculate transportation cost.",
			"thumb":"50.png",
            "id": 50
        }, {
            "title": "Select a Truck for a Move",
            "category": "Transportation",
            "description": "Select a truck for a move based on the weight and volume of the load.",
			"thumb":"51.png",
            "id": 51
        }, {
            "title": "Car Purchase vs Lease Calculator",
            "category": "Financial|Transportation",
            "description": "Compare the financial implications of purchasing versus leasing a vehicle based on your inputs (Generated by Claude AI).",
			"thumb":"75.png",
            "id": 75
        }, {
            "title": "List of Universities",
            "category": "Education",
            "description": "Compile a comprehensive list of the existing universities in each country.",
			"thumb":"63.png",
            "id": 63
        }, {
            "title": "Typewriter",
            "category": "Education",
            "description": "Perfect your typing performance.",
			"thumb":"64.png",
            "id": 64
        }, {
            "title": "Openwhyd Playlist",
            "category": "Service",
            "description": "Loads the media playlist from the Openwhyd service.",
			"thumb":"65.png",
            "id": 65
        }, {
            "title": "Archive.org",
            "category": "Service",
            "description": "Search for metadata in Archive.org.",
			"thumb":"66.png",
            "id": 66
        }, {
            "title": "Facts About Numbers",
            "category": "Service|Education",
            "description": "Expand your knowledge with fascinating random number facts. New fact every X seconds.",
			"thumb":"67.png",
            "id": 67
        }
    ],
    "pro": [
    ],
    "dev": [{
            "title": "Mortgage Calculator",
            "category": "Financial",
            "description": "The mortgage calculator uses the financial operations module to calculate the monthly payment and generate the amortization schedule.",
			"thumb":"9.png",
            "id": 9
        }, {
            "title": "Compound Interest Calculator (With line chart)",
            "category": "Financial",
            "description": "Calculates the compound interest and draws a line chart with the evolution.",
			"thumb":"12.png",
            "id": 12
        }, {
            "title": "SIP Investment Calculator with Stacked Bar",
            "category": "Financial",
            "description": "Calculate the invested amount, estimated return, and the total value.",
			"thumb":"36.png",
            "id": 36
        }, {
            "title": "Cab Service (DISTANCE operation)",
            "category": "Distance",
            "description": "Determines the distance in miles between two addresses and multiplies it by the cost per mile.",
			"thumb":"15.png",
            "id": 15
        }, {
            "title": "Filtering Posts",
            "category": "Data Sources",
            "description": "Use DS fields for filtering website posts and pages.",
			"thumb":"16.png",
            "id": 16
        }, {
            "title": "Registered User Information",
            "category": "Data Sources",
            "description": "Gets the registered user information from the database using DS fields.",
			"thumb":"18.png",
            "id": 18
        }, {
            "title": "Filtering WooCommerce Products",
            "category": "WooCommerce",
            "description": "The form filters WooCommerce products based on search terms.",
			"thumb":"37.png",
            "id": 37
        }, {
            "title": "WooCommerce Buyers List",
            "category": "WooCommerce",
            "description": "Retrieve buyer emails, product quantities, and total amounts per buyer.",
			"thumb":"40.png",
            "id": 40
        }
    ],
    "plat": [
    ]
};
